### ISSUE TITLE
Parts of map missing

### ISSUE THREAD

**Issue by smash2410** [quai20/argoApp#16]
HTC U11+
Parts of the map is missing?
See attachment.
![Screenshot_20210418-154242](https://user-images.githubusercontent.com/82746946/115135669-77f6d580-a05d-11eb-848e-bb53265b72ce.png)

**Comment by quai20** [comment]
Hi @smash2410 
does the issue persist when you zoom/unzoom ?

**Comment by smash2410** [comment]
It's was still the same, it seems the issue has been fixed

**Comment by smash2410** [comment]
![Uploading Screenshot_20210418-231006.png…]()

**Comment by quai20** [comment]
Can I ask how did you heard about the app ?
